import { taskDeepLink } from './state';
import type { TaskRouteIntent } from './types';

/** The small clipboard surface the share actions need (and tests can provide). */
export type ClipboardWriter = {
  writeText: (value: string) => PromiseLike<void> | void;
};

export type CopyTextResult =
  | { ok: true; value: string }
  | { ok: false; value: string; reason: 'unavailable' | 'denied' };

export type TaskShareUrlOptions = {
  /** The current app origin. Its path, query, and fragment are discarded. */
  origin?: string;
  /** Preserve the route's explicit activity intent when sharing from that tab. */
  intent?: TaskRouteIntent;
};

/**
 * Build an absolute, bookmarkable task URL from the existing task route.
 *
 * Only the origin is taken from the current location. The route itself is
 * generated by taskDeepLink, so board filters, auth/query values, and hashes
 * cannot accidentally become part of a copied task URL.
 */
export function buildTaskShareUrl(
  projectSlug: string,
  taskReference: string,
  options: TaskShareUrlOptions = {}
): string {
  const slug = projectSlug.trim();
  const reference = taskReference.trim();
  if (!slug || !reference) return '';

  const route = taskDeepLink(slug, reference, options.intent || 'details');
  const origin = options.origin === undefined
    ? typeof window !== 'undefined' ? window.location.origin : ''
    : options.origin.trim();
  if (!origin) return route;

  try {
    const base = new URL(origin);
    if (!/^https?:$/.test(base.protocol)) return route;
    return new URL(route, base.origin).toString();
  } catch {
    // The relative route is still safe and useful if the origin is unavailable
    // or malformed (for example during a pre-rendered shell test).
    return route;
  }
}

function browserClipboard(): ClipboardWriter | null {
  if (typeof navigator === 'undefined') return null;
  const candidate = (navigator as Navigator & { clipboard?: Partial<Clipboard> }).clipboard;
  return candidate && typeof candidate.writeText === 'function'
    ? candidate as ClipboardWriter
    : null;
}

/**
 * Copy text without claiming success when clipboard access is unavailable or
 * denied. Passing null explicitly is useful for testing the manual fallback.
 */
export async function copyText(
  value: string,
  clipboard?: ClipboardWriter | null
): Promise<CopyTextResult> {
  if (!value.trim()) return { ok: false, value, reason: 'unavailable' };
  const writer = clipboard === undefined ? browserClipboard() : clipboard;
  if (!writer || typeof writer.writeText !== 'function') {
    return { ok: false, value, reason: 'unavailable' };
  }

  try {
    await writer.writeText(value);
    return { ok: true, value };
  } catch {
    return { ok: false, value, reason: 'denied' };
  }
}
